name: code_gen
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  code_gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Run codegen
        run: devenv tasks run go:gen
      - name: Check for changes
        run: |
          chmod +x ./build/ci-scripts/assert-no-diff.sh
          ./build/ci-scripts/assert-no-diff.sh
        shell: bash
