name: run_tests
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Run tests
        run: devenv tasks run go:test-ci
