package diff

import (
	"fmt"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/stripe/pg-schema-diff/internal/schema"
	"github.com/stripe/pg-schema-diff/internal/testdb"
)

func TestArchivalIsolationPostgresACLForeignKeyPublicationAndStatistics(t *testing.T) {
	factory := testdb.MustNewFactory(t)
	roleNames := []string{
		"stage14_grantor", "stage14_second", "stage14_reader", "stage14_default_reader",
	}
	roleGuard := factory.LockRoles(t, roleNames...)
	roleGuard.CreateRoles()
	currentDB := factory.CreateDatabase(t)
	targetDB := factory.CreateDatabase(t)

	_, err := currentDB.ConnPool.Exec(t.Context(), `
		ALTER DEFAULT PRIVILEGES GRANT UPDATE ON TABLES TO stage14_default_reader;
		CREATE TABLE public.stage14_parent (id bigint PRIMARY KEY);
		INSERT INTO public.stage14_parent VALUES (1), (2);
		CREATE TABLE public.stage14_accounts (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			payload text NOT NULL,
			self_id bigint,
			no_action_id bigint,
			cascade_id bigint,
			set_null_id bigint,
			set_default_id bigint DEFAULT 1,
			CONSTRAINT stage14_accounts_self_fk FOREIGN KEY (self_id)
				REFERENCES public.stage14_accounts(id),
			CONSTRAINT stage14_accounts_no_action_fk FOREIGN KEY (no_action_id)
				REFERENCES public.stage14_parent(id),
			CONSTRAINT stage14_accounts_cascade_fk FOREIGN KEY (cascade_id)
				REFERENCES public.stage14_parent(id) ON DELETE CASCADE,
			CONSTRAINT stage14_accounts_set_null_fk FOREIGN KEY (set_null_id)
				REFERENCES public.stage14_parent(id) ON DELETE SET NULL,
			CONSTRAINT stage14_accounts_set_default_fk FOREIGN KEY (set_default_id)
				REFERENCES public.stage14_parent(id) ON DELETE SET DEFAULT
		);
		CREATE TABLE public.stage14_incoming_no_action (
			id bigint PRIMARY KEY, account_id bigint REFERENCES public.stage14_accounts(id)
		);
		CREATE TABLE public.stage14_incoming_cascade (
			id bigint PRIMARY KEY, account_id bigint REFERENCES public.stage14_accounts(id) ON DELETE CASCADE
		);
		CREATE TABLE public.stage14_incoming_set_null (
			id bigint PRIMARY KEY, account_id bigint REFERENCES public.stage14_accounts(id) ON DELETE SET NULL
		);
		CREATE TABLE public.stage14_incoming_set_default (
			id bigint PRIMARY KEY, account_id bigint DEFAULT 1
				REFERENCES public.stage14_accounts(id) ON DELETE SET DEFAULT
		);
		CREATE STATISTICS public.stage14_accounts_stats (dependencies)
			ON id, payload FROM public.stage14_accounts;
		CREATE STATISTICS public.stage14_accounts_expression_stats
			ON (lower(payload)) FROM public.stage14_accounts;
		INSERT INTO public.stage14_accounts (payload, self_id, no_action_id, cascade_id, set_null_id, set_default_id)
			VALUES ('retained', NULL, 1, 1, 1, 1);
		GRANT SELECT ON public.stage14_accounts TO PUBLIC;
		GRANT SELECT ON public.stage14_accounts TO stage14_grantor WITH GRANT OPTION;
		SET ROLE stage14_grantor;
		GRANT SELECT ON public.stage14_accounts TO stage14_second WITH GRANT OPTION;
		GRANT SELECT (payload) ON public.stage14_accounts TO stage14_reader;
		RESET ROLE;
		SET ROLE stage14_second;
		GRANT SELECT ON public.stage14_accounts TO stage14_reader;
		RESET ROLE;
		GRANT USAGE ON SEQUENCE public.stage14_accounts_id_seq TO PUBLIC;
		GRANT SELECT ON SEQUENCE public.stage14_accounts_id_seq TO stage14_reader;
		CREATE PUBLICATION stage14_explicit_publication
			FOR TABLE public.stage14_accounts (id, payload) WHERE (id > 0);
		CREATE PUBLICATION stage14_schema_publication FOR TABLES IN SCHEMA public;
	`)
	require.NoError(t, err)

	_, err = targetDB.ConnPool.Exec(t.Context(), `
		CREATE TABLE public.stage14_parent (id bigint PRIMARY KEY);
		INSERT INTO public.stage14_parent VALUES (1), (2);
		CREATE TABLE public.stage14_accounts (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			payload text NOT NULL,
			self_id bigint,
			CONSTRAINT stage14_accounts_self_fk FOREIGN KEY (self_id)
				REFERENCES public.stage14_accounts(id)
		) PARTITION BY HASH (id);
		CREATE TABLE public.stage14_incoming_no_action (
			id bigint PRIMARY KEY, account_id bigint REFERENCES public.stage14_accounts(id)
		);
		CREATE TABLE public.stage14_incoming_cascade (
			id bigint PRIMARY KEY, account_id bigint REFERENCES public.stage14_accounts(id) ON DELETE CASCADE
		);
		CREATE TABLE public.stage14_incoming_set_null (
			id bigint PRIMARY KEY, account_id bigint REFERENCES public.stage14_accounts(id) ON DELETE SET NULL
		);
		CREATE TABLE public.stage14_incoming_set_default (
			id bigint PRIMARY KEY, account_id bigint DEFAULT 1
				REFERENCES public.stage14_accounts(id) ON DELETE SET DEFAULT
		);
	`)
	require.NoError(t, err)

	current, err := schema.GetSchemaSnapshot(t.Context(), currentDB.ConnPool)
	require.NoError(t, err)
	target, err := schema.GetSchemaSnapshot(t.Context(), targetDB.ConnPool)
	require.NoError(t, err)
	relation := mustCatalogRelationByName(t, current.Inventory, "public", "stage14_accounts")
	request, marker := stage14ArchivalDatabaseRequest(
		t, current, target, relation, "20260721T091011123456Z_ABCDEFGH",
	)
	diff, _, err := buildSchemaDiff(current.Schema, target.Schema)
	require.NoError(t, err)
	statements, err := generateReplacementAwareSchemaSQL(
		newSchemaSQLGenerator(&deterministicRandReader{}, &planOptions{}), diff,
		tableDispositions{schema.SchemaQualifiedName{
			SchemaName: "public", EscapedName: schema.EscapeIdentifier("stage14_accounts"),
		}.GetName(): {
			Kind: tableDispositionKindArchivalMove, GroupID: marker.GroupID,
			RelationOID: relation.OID,
		}},
		request,
	)
	require.NoError(t, err)
	assertReplacementAwareStatementsAreNonDestructive(t, statements)

	moveIndex := statementIndexContaining(t, statements,
		`ALTER TABLE "public"."stage14_accounts" SET SCHEMA`)
	createReplacementIndex := statementIndexContaining(t, statements,
		`CREATE TABLE "public"."stage14_accounts"`)
	replacementPrimaryKey := statementIndexContaining(t, statements,
		`ADD CONSTRAINT "stage14_accounts_pkey" PRIMARY KEY`)
	assert.Less(t, moveIndex, createReplacementIndex)
	for _, foreignKey := range request.SourcePreflight.ForeignKeys {
		if foreignKey.Direction == sourceSafetyForeignKeyDirectionSelf {
			continue
		}
		dropIndex := statementIndexContaining(t, statements,
			"DROP CONSTRAINT "+schema.EscapeIdentifier(foreignKey.ForeignKey.Name))
		assert.Less(t, dropIndex, moveIndex, foreignKey.ForeignKey.Name)
		assert.Equal(t, migrationHazardBoundaryForeignKeyDrop, statements[dropIndex].Hazards)
		if foreignKey.Direction == sourceSafetyForeignKeyDirectionIncoming {
			addIndex := lastStatementIndexContaining(t, statements,
				"ADD CONSTRAINT "+schema.EscapeIdentifier(foreignKey.ForeignKey.Name))
			assert.Less(t, createReplacementIndex, addIndex, foreignKey.ForeignKey.Name)
			assert.Less(t, replacementPrimaryKey, addIndex, foreignKey.ForeignKey.Name)
		}
	}
	for _, outgoingName := range []string{
		"stage14_accounts_no_action_fk", "stage14_accounts_cascade_fk",
		"stage14_accounts_set_null_fk", "stage14_accounts_set_default_fk",
	} {
		assert.NotContains(t, replacementAwareDDL(statements),
			"ADD CONSTRAINT "+schema.EscapeIdentifier(outgoingName))
	}
	for _, statisticName := range []string{"stage14_accounts_stats", "stage14_accounts_expression_stats"} {
		statisticMove := statementIndexContaining(t, statements,
			`ALTER STATISTICS "public".`+schema.EscapeIdentifier(statisticName)+` SET SCHEMA`)
		assert.Less(t, moveIndex, statisticMove)
	}
	for _, statement := range statements {
		_, err = currentDB.ConnPool.Exec(t.Context(), statement.ToSQL())
		require.NoErrorf(t, err, "executing statement:\n%s", statement.DDL)
	}

	cleanupSchema := marker.Members[0].CleanupTable.SchemaName
	var retainedPayload string
	err = currentDB.ConnPool.QueryRow(t.Context(), fmt.Sprintf(
		"SELECT payload FROM %s.stage14_accounts WHERE id = 1",
		schema.EscapeIdentifier(cleanupSchema),
	)).Scan(&retainedPayload)
	require.NoError(t, err)
	assert.Equal(t, "retained", retainedPayload)
	assert.NotZero(t, postgresRelationOID(t, currentDB.ConnPool, "public", "stage14_accounts"))

	var nonOwnerGrants int
	err = currentDB.ConnPool.QueryRow(t.Context(), `
		SELECT count(*)
		FROM pg_catalog.pg_class AS c
		CROSS JOIN LATERAL pg_catalog.aclexplode(
			COALESCE(c.relacl, pg_catalog.acldefault(
				(CASE c.relkind WHEN 'S' THEN 'S' ELSE 'r' END)::"char", c.relowner
			))
		) AS acl
		WHERE c.oid = ANY($1::oid[]) AND acl.grantee <> c.relowner
	`, []uint32{relation.OID, catalogSequenceByNameForStage14(t, current.Inventory,
		"public", "stage14_accounts_id_seq").OID}).Scan(&nonOwnerGrants)
	require.NoError(t, err)
	assert.Zero(t, nonOwnerGrants)

	for _, publicationName := range []string{"stage14_explicit_publication", "stage14_schema_publication"} {
		var published bool
		err = currentDB.ConnPool.QueryRow(t.Context(), `
			SELECT EXISTS (
				SELECT 1 FROM pg_catalog.pg_publication AS p
				WHERE p.pubname = $2 AND (
					EXISTS (SELECT 1 FROM pg_catalog.pg_publication_rel AS pr
						WHERE pr.prpubid = p.oid AND pr.prrelid = $1)
					OR EXISTS (
						SELECT 1 FROM pg_catalog.pg_class AS c
						JOIN pg_catalog.pg_publication_namespace AS publication_namespace
							ON publication_namespace.pnnspid = c.relnamespace
						WHERE publication_namespace.pnpubid = p.oid AND c.oid = $1
					)
				)
			)
		`, relation.OID, publicationName).Scan(&published)
		require.NoError(t, err)
		assert.False(t, published, publicationName)
	}
	assert.Equal(t, relation.OID,
		postgresRelationOID(t, currentDB.ConnPool, cleanupSchema, "stage14_accounts"))
}

func TestArchivalIsolationPostgresMovesDependencyClosure(t *testing.T) {
	factory := testdb.MustNewFactory(t)
	currentDB := factory.CreateDatabase(t)
	targetDB := factory.CreateDatabase(t)
	_, err := currentDB.ConnPool.Exec(t.Context(), `
		CREATE SCHEMA managed;
		CREATE SCHEMA deps;
		CREATE TYPE deps.status AS ENUM ('ready', 'done');
		CREATE DOMAIN deps.positive AS integer CHECK (VALUE > 0);
		CREATE TYPE deps.pair AS (amount deps.positive, label text);
		CREATE TYPE deps.int_span AS RANGE (SUBTYPE = integer);
		CREATE COLLATION deps.c_copy FROM "C";
		CREATE FUNCTION deps.identity_value(value integer)
			RETURNS integer LANGUAGE SQL IMMUTABLE RETURN value;
		CREATE FUNCTION deps.integer_equal(left_value integer, right_value integer)
			RETURNS boolean LANGUAGE SQL IMMUTABLE RETURN left_value = right_value;
		CREATE OPERATOR deps.=== (
			LEFTARG = integer, RIGHTARG = integer, FUNCTION = deps.integer_equal
		);
		CREATE SEQUENCE deps.standalone_numbers;
		CREATE TABLE managed.stage14_dependency_table (
			id bigint DEFAULT nextval('deps.standalone_numbers'),
			status deps.status,
			positive deps.positive,
			pair deps.pair,
			span deps.int_span,
			spans deps.int_span_multirange,
			label text COLLATE deps.c_copy,
			compared integer DEFAULT deps.identity_value(1),
			CHECK (compared OPERATOR(deps.===) compared)
		);
		CREATE STATISTICS managed.stage14_dependency_stats (dependencies)
			ON status, compared FROM managed.stage14_dependency_table;
		CREATE STATISTICS managed.stage14_dependency_expression_stats
			ON (lower(label)) FROM managed.stage14_dependency_table;
		INSERT INTO managed.stage14_dependency_table (status, positive, pair, span, spans, label)
		VALUES ('ready', 1, ROW(2, 'pair'), '[1,3)', '{[1,3)}', 'retained');
	`)
	require.NoError(t, err)
	current, err := schema.GetSchemaSnapshot(t.Context(), currentDB.ConnPool)
	require.NoError(t, err)
	target, err := schema.GetSchemaSnapshot(t.Context(), targetDB.ConnPool)
	require.NoError(t, err)
	relation := mustCatalogRelationByName(t, current.Inventory, "managed", "stage14_dependency_table")
	request, marker := stage14ArchivalDatabaseRequest(
		t, current, target, relation, "20260721T091011123456Z_12345678",
	)
	diff, _, err := buildSchemaDiff(current.Schema, target.Schema)
	require.NoError(t, err)
	statements, err := generateReplacementAwareSchemaSQL(
		newSchemaSQLGenerator(&deterministicRandReader{}, &planOptions{}), diff,
		tableDispositions{current.Schema.Tables[0].GetName(): {
			Kind: tableDispositionKindArchivalMove, GroupID: marker.GroupID, RelationOID: relation.OID,
		}}, request,
	)
	require.NoError(t, err)
	moveIndex := statementIndexContaining(t, statements,
		`ALTER TABLE "managed"."stage14_dependency_table" SET SCHEMA`)
	for _, assignment := range request.DependencyClosure.Assignments {
		move := statementIndexContaining(t, statements,
			"SET SCHEMA "+schema.EscapeIdentifier(assignment.Destination.SchemaName))
		assert.Less(t, moveIndex, move, assignment.Source.Name)
	}
	for _, statement := range statements {
		_, err = currentDB.ConnPool.Exec(t.Context(), statement.ToSQL())
		require.NoErrorf(t, err, "executing statement:\n%s", statement.DDL)
	}

	dependencySchema := marker.ExclusiveDependencySchemas[0].Name
	for _, assignment := range request.DependencyClosure.Assignments {
		actual, count := currentCatalogObjectsWithOID(
			mustSchemaSnapshot(t, currentDB.ConnPool).Inventory, assignment.Destination.Kind,
			assignment.Destination.OID,
		)
		assert.Equal(t, 1, count, assignment.Source.Name)
		assert.Equal(t, dependencySchema, actual.SchemaName, assignment.Source.Name)
	}
	cleanupSchema := marker.Members[0].CleanupTable.SchemaName
	var rowCount int
	err = currentDB.ConnPool.QueryRow(t.Context(), fmt.Sprintf(
		"SELECT count(*) FROM %s.stage14_dependency_table",
		schema.EscapeIdentifier(cleanupSchema),
	)).Scan(&rowCount)
	require.NoError(t, err)
	assert.Equal(t, 1, rowCount)
}

func stage14ArchivalDatabaseRequest(
	t *testing.T,
	current schema.SchemaSnapshot,
	target schema.SchemaSnapshot,
	relation schema.CatalogRelation,
	groupID archivalGroupID,
) (plainTableArchivalRequest, archivalMarkerV1) {
	t.Helper()
	request, _ := plainTableArchivalDatabaseRequest(t, current.Inventory, relation, groupID)
	preflight, err := runSourceSafetyPreflight(sourceSafetyPreflightRequest{
		CurrentSnapshot: current, TargetSnapshot: target,
		ProposedTableRelationOIDs: []uint32{relation.OID},
	})
	require.NoError(t, err)
	closure, err := planArchivedDependencyClosure(archivedDependencyClosureRequest{
		CurrentSnapshot: current, TargetSnapshot: target, SourcePreflight: preflight,
		ProposedGroups: []archivedDependencyClosureGroupRequest{{
			GroupID: groupID, TableRelationOIDs: []uint32{relation.OID},
			DependencySchemaName: request.Groups[0].Allocation.DependencySchemaName,
		}},
	})
	require.NoError(t, err)
	request.SourcePreflight = preflight
	request.DependencyClosure = closure
	request.TargetSchema = target.Schema
	request = finalizeArchivalIsolationUnitMarker(t, request)
	marker, err := parseArchivalMarker(request.Groups[0].FinalizedMarker)
	require.NoError(t, err)
	return request, marker
}

func lastStatementIndexContaining(t *testing.T, statements []Statement, fragment string) int {
	t.Helper()
	for idx := len(statements) - 1; idx >= 0; idx-- {
		if strings.Contains(statements[idx].DDL, fragment) {
			return idx
		}
	}
	require.FailNow(t, "statement not found", "fragment: %s", fragment)
	return -1
}

func catalogSequenceByNameForStage14(
	t *testing.T,
	inventory schema.CatalogInventory,
	schemaName string,
	name string,
) schema.CatalogSequence {
	t.Helper()
	for _, sequence := range inventory.Sequences {
		if sequence.SchemaName == schemaName && sequence.Name == name {
			return sequence
		}
	}
	require.FailNow(t, "sequence not found", "%s.%s", schemaName, name)
	return schema.CatalogSequence{}
}

func mustSchemaSnapshot(t *testing.T, pool *pgxpool.Pool) schema.SchemaSnapshot {
	t.Helper()
	snapshot, err := schema.GetSchemaSnapshot(t.Context(), pool)
	require.NoError(t, err)
	return snapshot
}
